s = set("123 ABC")
t = set("135 AZ")
intersect = s & t # or s.intersection(t)
exclusion = s ^ t # or s.symmetric_difference(t)
a_minus_b = s - t # or s.difference(t)
b_minus_a = t - s # or t.difference(s)
print(s)
print(t)
print("Intersection: {}".format(intersect))
print("Exclusion: {}".format(exclusion))
print("a - b: {}".format(a_minus_b))
print("b - a: {}".format(b_minus_a))